cache_directory: log/cache
cache_gigs: 3
du_path: du
ecasound_path: ecasound
error_directory: log/error
ffmpeg_path: ffmpeg
keep_temporary_files: true
log_directory: log/moviemasher
log_level: debug
process_queues_seconds: 55
queue_directory: /Library/WebServer/stage.moviemasher.com/DemoAngular/MovieMasherQueue
queue_idle_timeout: 40
queue_initial_timeout: nil
queue_visibility_timeout: 360
s3_read_at_once: true
sox_path: sox
temporary_directory: log/temporary
wav2png_path: wav2png
