cache_gigs: 3
dir_cache: log/cache
dir_error: log/error
dir_log: log/moviemasher
dir_queue: /Library/WebServer/stage.moviemasher.com/DemoAngular/MovieMasherQueue
dir_temporary: log/temporary
keep_temporary_files: true
log_level: debug
path_du: du
path_ecasound: ecasound
path_ffmpeg: ffmpeg
path_sox: sox
path_wav2png: wav2png
process_queues_seconds: 55
queue_idle_timeout: 40
queue_initial_timeout: nil
queue_visibility_timeout: 360
s3_read_at_once: true
