cache_directory: /tmp/moviemasher/cache
cache_gigs: 3
chmod_directory_new: 0775
du_path: du
ecasound_path: ecasound
error_directory: 
ffmpeg_path: ffmpeg
keep_temporary_files: false
log_directory: /var/log/moviemasher
log_level: info
process_queues_seconds: 55
queue_directory: /tmp/moviemasher/queue
queue_idle_timeout: 40
queue_initial_timeout: 
queue_visibility_timeout: 360
queue_wait_time_seconds: 2
sox_path: sox
temporary_directory: /tmp/moviemasher/temporary
wav2png_path: wav2png
