 # chmod_directory_new: 0775
 # error_directory:
 # render_keep: false
 # log_level: info
 # process_queues_seconds: 55
 # queue_wait_time_seconds: 2
download_directory_size: 3
download_directory: /tmp/moviemasher/cache
log_directory: /var/log/moviemasher
queue_directory: /tmp/moviemasher/queue
render_directory: /tmp/moviemasher/temporary
